frontend/src/components/navbar.svelte, frontend/src/routes/index.svelte
You can choose `Choose country` as country in the navbar.
Try to click choose country in the navbar
It should be disabled
_No response_
=> Choose country in navbar not disabled & remove countryCode from title

frontend/src/routes/index.svelte, frontend/src/utils.ts
Fetch functions are now called in onMount which should fix the issue with genres not being loaded quickly enough
when user goes back to index-page.
Also fixes extra loadtime for multiselects by initializing values before components are loaded in.
Moved dict-function back to utils.js.
=> Sessionstore now works for genres and multiselects load quicker

frontend/src/routes/index.svelte
Multiselects atm give a error on page load:
Go to the site and look at console log
No errors from multiselects on page load
_No response_
=> Console log mulitiselect spam

frontend/src/routes/__error.svelte
In firefox the error page will shortly show itself whjen loading a page since it gets the dynamic import error
Go to index page
Route anywhere else in the program
Repeat
Error page should not be shown if the request is succesful
This is a temp fix that just delays the error page
=> Firefox dynamic import loads error page

frontend/src/routes/index.svelte
Right now if you find a media with 6 or more providers the `+ number` providers will always show the total amount of providers - 1
Go to index page
Find a movie/tv serie with 6 or more providers
It should show the correct amount of providers
_No response_
=> + number providers doesnt work

backend/app/cli.py, backend/app/db/database_service.py
It's annoying not being able to see if meilisearch is stalling or actually indexing, adding some print statements for
what it is indexing would be nice.
Add print statements to the meilisearch indexing step
_No response_
_No response_
=> Add print statements for meilisearch indexing

frontend/src/components/no_results.svelte, frontend/src/routes/index.svelte
I would like to see what genres/providers i have selected when getting no results on index page
Having the list of genres & providers you have chosen shown when no results pops up
_No response_
_No response_
=> Genre & providers shown in no results on index page

frontend/src/utils.ts
When you go to a recommendation and and wants to go back, you will end up on the bottom of the page instead
1. Go to a TV-show or movie
2. Click on a recommendation
3. Click previous page
4. Goes to bottom of page instead of previous page
_No response_
_No response_
=> Fix recommendations breaking previous page

frontend/src/components/read_more.svelte, frontend/src/routes/movie/[id].svelte, frontend/src/routes/person/[id].svelte, frontend/src/routes/tv/[id].svelte
Right now the detailsview descriptions can get very long and out of hand. 
https://streamchaser.tv/person/18918
If like the description length was fixed, and you could simply press `show more` to get the full description
_No response_
_No response_
=> Handle long descriptions in detailsview

frontend/src/components/details/recommendations.svelte, frontend/src/components/loading/spinner.svelte, frontend/src/routes/movie/[id].svelte, frontend/src/routes/person/[id].svelte, frontend/src/routes/tv/[id].svelte
This adds a spinner for loading instead of the ugly `P` tag. 
This also fixes `tv` recommendation where they redirected incorrectly #26
=> Add spinner for loading details view & fix recommendations for tv

frontend/src/components/details/read_more.svelte, frontend/src/components/details/top_card.svelte, frontend/src/components/error.svelte, frontend/src/components/footer.svelte
Right now the card on details views uses glass blur. This is disabled by default in fx. `firefox`, and makes it very hard to read the content of the card.
https://streamchaser.tv/tv/93405
Even sometimes in browsers that support glass blur it can be hard to decode what is inside the card.
https://streamchaser.tv/person/56730
I would like a detailsview card where we can always see the content of the card. Furthermore a solution that supports all browsers by default.
_No response_
_No response_
=> Better handling of card in detailsview

frontend/src/components/media_search.svelte
Right now the No results for pops up instantly when page loads before we get any media hits.
1. Go to https://streamchaser.tv
2. See the No Results pop up instantly
No results should not pop up instantly, it should appear only after genres, input or providers is given
_No response_
=> No results pop up on page launch

backend/app/api.py
Right now when we download the json.gz files in [api.py](https://github.com/streamchaser/streamchaser/blob/master/backend/app/api.py), we generate the current date, and keep going 1 day back if there are no files that current day. This works perfectly fine, but where it breaks is if the months or day is single digit. tmdb requires the request format to have 2 digits even tho the date or month only has 1 digit. 
This results in streamchaser now fails to download files multiple times, until it hits the 31 january 2021, since the format fits then.
```
❯ docker-compose exec backend python3 cli.py full-setup 500
Downloading dumps: 2022-01-18
http://files.tmdb.org/p/exports/tv_series_ids_1_18_2022.json.gz
http://files.tmdb.org/p/exports/movie_ids_1_18_2022.json.gz
Downloads failed - trying 1 …
```
=> Full-setup not fetching newest json.gz files from tmdb

frontend/src/components/details/person.svelte, frontend/src/components/details/person_media.svelte, frontend/src/components/details/recommendations.svelte, frontend/src/components/media_search.svelte, frontend/src/utils.ts
Right now we cannot open new tabs with control or any of the other standard browser ways. This needs to change.
All the places where this should be supported should use a `a href` instead if a `div`.
[This pull request](https://github.com/streamchaser/streamchaser/pull/119) started the idea
=> Support for opening new tabs with ctrl/mid mouse/shift

frontend/src/components/details/top_card.svelte, frontend/src/routes/movie/[id].svelte, frontend/src/routes/person/[id].svelte, frontend/src/routes/tv/[id].svelte
Right now on the card in detailsview we only show `title`, `description`, `poster_path` & `genres`. We could add a lot more to the card.
I would like for movies & tv to have `release date`, `director` and maybe other interesting stuff! Be creative! 
_No response_
_No response_
=> More info on card in detailsview

frontend/src/components/details/recommendations.svelte
So yeah, the issue is back.. Recommendations only change the url, but does not redirect. It seems that in recommendations the  `target` is not being set properly for some reason. Adding it manually fixes the issue
=> Fix recommendations not redirecting

backend/app/cli.py, backend/app/db/database_service.py
USA isn't being indexed by meilisearch because our new dataset is creates a payload too large for meilisearch to handle - It needs to be chunked (will also optimize the current RAM bottleneck)
1. Have a full-setup with popularity 1
2. Update the data
3. Watch USA fail
_No response_
```
root@prod:~/streamchaser# docker-compose exec -T backend python3 cli.py index-meilisearch
Meilisearch is indexing...
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/meilisearch/_httprequests.py", line 91, in __validate
request.raise_for_status()
File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 953, in raise_for_status
raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 413 Client Error: Payload Too Large for url: …
```
=> Meilisearch unable to index because of too large payload

frontend/src/components/details/top_card.svelte, frontend/src/components/media_search.svelte
Right now we dont handle media with no poster path very well.
(from searching for harry potter)
I would like to have them have a static colored background with the title of the media as text on the background. This will make it look less odd, and not loose any media.
_No response_
_No response_
=> Better handling of media with no poster path

frontend/Dockerfile, frontend/package-lock.json, frontend/package.json, frontend/postcss.config.cjs, frontend/src/app.css, frontend/src/app.html, frontend/src/routes/__layout.svelte, frontend/tailwind.config.cjs
Right now we use `CDN` for `tailwindcss` & `daisyui`. We should use the official way.
Stop using CDN and properly install `tailwindcss` & `daisyui`
=> Stop use of CDN in frontend

docker-compose.yml
* Bumps the MeiliSearch version to 0.25.2
=> Up MeiliSearch version to 0.25.2 - M1 support

frontend/src/components/media_search.svelte
This adds TV on the cards for TV shows. This makes it easier to locate what media is TV and what is movies.
=> Add TV for the media cards that are TV on index page

frontend/src/components/cookie_disclaimer.svelte
* Adds a fade + fly in/out effect to the cookie disclaimer
The one from here https://svelte.dev/tutorial/in-and-out
=> Add transitions to cookie disclaimer

frontend/src/routes/__layout.svelte
before:
after:
This also fixes misalignment of seasons component
=> Fixed alignment of page content 

.gitignore, .pre-commit-config.yaml, backend/app/api.py, backend/app/api_helpers.py, backend/app/db/crud.py, backend/app/db/database_service.py, backend/app/db/models.py, backend/app/db/search.py, backend/app/routers/providers.py, backend/app/routers/search.py, backend/app/schemas.py, backend/app/util.py, frontend/src/components/details/top_card.svelte, frontend/src/components/media_search.svelte, frontend/src/routes/index.svelte, frontend/src/routes/movie/[id].svelte, frontend/src/routes/tv/[id].svelte, frontend/src/utils.ts
We should be able to support free providers like `DRTV`. There are a lot of people seeking content through free providers like `viafree` and so on, and we are loosing a lot by not giving them the information they need to stream now!
right now in `api_helpers.py`, we filter for only `flatrate`, and here we could easily add `free` aswell.
```python
def get_providers(providers: Dict, country_code: str = 'all') -> List[Dict]:
""" Gets list of provider data for a movie from a specified country code
"""
try:
if country_code == 'all':
return [
{country: provider}
for country in providers.get('results')
if providers.get('results').get(country).get('flatrate')
for provider in providers.get('results').get(country).get('flatrate')
]
return [
provider
for provider in …
```
=> Add free providers

frontend/src/components/loading/spinner.svelte, frontend/src/components/media_search.svelte
* Fixes misleading NoResults while loading
Before:
After:
=> Fix index showing No results for: <No input> while loading

frontend/package.json, frontend/src/components/details/person.svelte, frontend/src/components/details/person_media.svelte, frontend/src/components/media_search.svelte, frontend/src/routes/index.svelte, frontend/src/routes/person/[id].svelte, frontend/src/stores/limit.js, frontend/src/types.ts, frontend/src/utils.ts, frontend/yarn.lock
**Is your feature request related to a problem? Please describe.**
The amount of elements pr row logic is not the best ATM. 
**Describe the solution you'd like**
Right now we have 21 elements on our index page. This was the number because we would have 7 elements pr row, and then we have 3 rows. Since it is not a even number it will look ugly on mobile view half of the time. I want us to rethink how many items there should be pr row, and how many elements we should start our index page with. Furthermore we could also think about how many more items should appear when `show more` button is pressed.
=> Rethink amount of elements on rows in index page

docker-compose.yml
Meilisearch data is not persistent when downing the containers
1. docker-compose down
1a. docker-compose down search  // Alternative
3. docker-compose up
4. *Meilisearch indexes are gone*
Meilisearch keeps data when downed without the `-v`
https://docs.meilisearch.com/learn/getting_started/quick_start.html#step-1-setup-and-installation:
> Data written to a Docker container is not persistent and is wiped every time the container is stopped. We recommend using a shared Docker volume between containers and host machines to provide persistent storage.
Similar to how it's done with the other databases at the bottom of our docker-compose.yml
```yml
volumes:
pgdata:
node_modules:
cache:
driver: local
```
=> Meilisearch data is not persistent

backend/Dockerfile
Our backend doesn't send logs to stdout with the production environment(gunicorn)
1. `docker-compose logs -f backend`
2. Go-to `localhost` and watch the logs not do anything
The same status logs as in development
=> No logs over API calls in production

frontend/src/components/media_search.svelte, frontend/src/components/no_results.svelte
The out transition is delaying the detail page load
https://user-images.githubusercontent.com/43907402/156844556-b4c96d20-9644-4217-a3ae-6a76447a7e67.mov
1. Press a card
2. Wait 200ms for the cards to fade out
The page should load instantly
_No response_
=> Fade out transition delays page loading

backend/app/db/cache.py, backend/app/db/database_service.py, backend/app/routers/genres.py, backend/pyproject.toml, backend/tests/test_cache.py
Removes pydantic_aioredis, because it's a bit silly to have libraries that do the same
* Changes the way we store genres to be in one JSON, instead of a key for every genre
=> Change genres to use normal aioredis and be in one key

backend/app/db/database_service.py, backend/cli.py, docker-compose.yml
* Removes Postgres batch-streaming
* Changes payload size from 100mb to 1gb
Makes the whole Meilisearch indexing step happen in 1-go per country, which will save Meilisearch from re-indexing
This will eat a LOT of memory, but since we got plenty it won't be an issue.
=> Remove/simplify Meilisearch index batching

frontend/src/components/error.svelte, frontend/src/components/error_buttons.svelte, frontend/src/components/loading/spinner.svelte
If the user has gotten a faulty link from somewhere other than streamchaser, we should route them to the index and not back to where they came from(which would be nowhere if they were linked from Discord for example)
=> The error handling site should route back to the index page, if the user is linked to a dead link from an external source

backend/app/db/database_service.py, frontend/src/components/details/top_card.svelte
* Fixes an issue where clicking on the badge would break the multi selecting for genres
* Sorts genres alphabetically before putting them in Redis
=> Fix broken genre badge redirects plus sort genres

frontend/src/components/details/read_more.svelte, frontend/src/components/details/recommendations.svelte, frontend/src/components/details/seasons.svelte, frontend/src/components/details/top_card.svelte, frontend/src/components/no_results.svelte, frontend/src/routes/index.svelte
This PR does the following:
- Makes `read more...` button not redirect to top with a temp solution of removing the `href`
- Makes the background of recommendations on details not be rounded when on mobile view
- Makes the size of images of recommendations more consitant
- Removes mouse wheel scroll on recommendations
- Makes top card background not rounded on mobile view
- Fixes the `image_not_available` on Season cards where there is no image. Before the image was not shown, and it always showed the `alt tag`
- Made Season tabs not be large
- Centered the Season tabs on mobile too
- Adds Season title to the card on non-mobile view
- Makes the Season image not rounded on the right side on non mobile view
- Makes Season image sizes consistant
- Add a longer fade transition for `no_results` …
=> General frontend cleanups

backend/app/config.py, backend/app/db/database_service.py, backend/app/db/search.py, backend/app/routers/search.py, backend/app/schemas.py, backend/tests/conftest.py, backend/tests/test_filters.py
* Adds the ability to filter movies/tv and only get one of them
* Refactor of the old search endpoint logic - It's a lot more scalable now
* A bunch of tests and some things that will make it easier to add more
Fixes #40 to some extent - The issue is very vague
=> Add filtering of media types

frontend/src/components/filters.svelte
This fixes that the indicator goes out of mobile and makes the screen draggable to the sides.
=> Fix indicator icon going out of screen on mobile

frontend/src/components/filters.svelte
Make clear button dynamic, and turn off no providers toggle when providers are selected
=> Cleanup of filters component

backend/app/db/cache.py, backend/app/main.py, backend/app/routers/image.py, backend/poetry.lock, backend/pyproject.toml, frontend/src/lib/variables.js
Attempt to solve the 429 issue in a sane way 🙈 
- Adds an endpoint that gets posters from TMDB and caches them in Redis
- Only used on the W342 posters(search results, cast and recommendations) for now, which are the spammy ones
Fixes #277 #283
=> feat: add cached image proxy for posters

frontend/src/routes/+page.svelte
- Changes behavior of no input to not show media with no providers
- Changes some unnecessary formatted strings to normal string that annoyed me(yay a nanosecond more performant)
I've had this requested a few times
Fixes #137
=> feat: only show media with providers when no input

.github/dependabot.yml, backend/Dockerfile, backend/poetry.lock, backend/pyproject.toml
- Updated to Python 3.11
- Added Dependabot
- Updated all dependencies, beside meilisearch related ones see #272 
Fixes #318
=> feat!: up python to version 3.11, add dependabot and update dependencies

frontend/src/routes/+page.svelte
Makes themes usable again with correct itemColor
Fixes #
=> fix: multiselect is uwing wront itemcolor

frontend/src/lib/stores/preferences.ts
Quotation marks around store values of type string are kept when updating value in browser
Fixes #394
=> fix: missing quotation marks on stores of type string

backend/app/db/database_service.py, backend/cli.py, backend/poetry.lock, backend/pyproject.toml, docker-compose.yml
- Removes stale/dead media from Meilisearch
This should remove some of the adult things that TMDB remove too late, and stop the database from growing infinitely with junk media
=> feat: add command to remove stale media 

frontend/src/app.html, frontend/src/lib/components/cookie_disclaimer.svelte, frontend/src/lib/components/country_locator.svelte, frontend/src/lib/components/details/recommendations.svelte, frontend/src/lib/cookies.ts, frontend/src/lib/stores/cookies.ts, frontend/src/lib/stores/preferences.ts, frontend/src/lib/utils.ts, frontend/src/routes/+layout.svelte, frontend/src/routes/+page.svelte, frontend/src/routes/movie/[id]/+page.svelte, frontend/src/routes/tv/[id]/+page.svelte
Extends the CookieDisclaimer-component with options for disabling certain types of cookies.
Any store using LocalStorage will wait until consent is given before being initialized.
Clears LocalStorage if cookie consent is missing.
Fixes #298
=> feat: change cookiedisclaimer to include options for cookies

frontend/src/lib/components/navbar/phone_navbar.svelte, frontend/src/lib/components/theme_selector.svelte
Fixes theme selector that is unusable on mobile
=> fix: theme selector not opening on mobile

.pre-commit-config.yaml, backend/Dockerfile
- Removes the hack - Should be a performance boost for M1/M2 architectures
Background: We used to have an issue on M1 Macs when installing our Python dependencies because of psycopg. That is no longer an issue
=> chore: remove --platform Python hack

backend/app/api.py, backend/app/db/database_service.py, backend/cli.py, frontend/src/lib/components/filters.svelte, frontend/src/lib/components/media_card.svelte, frontend/src/lib/components/no_results.svelte, frontend/src/lib/stores/preferences.ts, frontend/src/routes/+page.svelte, internal/main.go, internal/routes.go, internal/types.go, justfile
This adds people to be searchable. This PR comes with some decisions that i am unsure if we want to continue with. For an example it adds people to the `media` index of meilisearch, but i am unsure if we want a separate one. I liked the idea of having one "master" index though.
Furthermore this adds quite a lot of API alls to `tmdb`, and makes the running through `json.gz` files take quite a lot longer since the new person file is quite long.
This also removes the `first-time` parameter of our `full-setup` since it was never used anyway. It is not triggered from providers being updated, and thus useless for us.
=> Add people to meilisearch media, and therefore searchable

justfile
`just cli <command>`
instead of
`docker-compose exec backend python3 cli.py <command>`
And defaults to --help when no command
=> feat: add QoL access to cli.py with 'just cli <command>'

frontend/package.json, frontend/yarn.lock
We are using Vite's 🦄  shiny preprocessor ✨
=> chore: remove svelte-preprocess (we use vite's now)

backend/app/db/database_service.py
Fixes this thing happening sometimes - killing the `full_setup`
=> fix: handle providers being empty sometimes

docker-compose.yml
We currently just pull the latest edgedb image, but it breaks our setup currently since they went to version 3.0. This pins the version to 2.7, which works.
=> fix: edgedb doesnt work with the new version 3. Pinned version to 2.7

frontend/package.json, frontend/src/lib/components/country_selector.svelte, frontend/src/lib/components/navbar/navbar.svelte, frontend/src/lib/components/search_dropdown.svelte, frontend/src/lib/components/svelte_select_css.svelte, frontend/src/routes/+page.svelte, frontend/yarn.lock
Adds search bar in navbar, when not on the index page, if screen size is above `1100px`.
Also updates our `svelte-select` version to the current one instead of our own forked version that is 2 majors behind. Furthermore also adds a component to add our `css` properties to the `svelte-select`.
Fixes #
#557
=> feat: update svelte-select and add search in navbar for large desktops

internal/routes.go
This stops us from processing media ane person with no images. They are usually unwanted or unknown and just adds a ton of media for us to index further down the line.
=> feat: stop processing media with no poster paths
