frontend/src/routes/about.svelte, frontend/src/routes/faq.svelte, frontend/src/routes/movie/[id].svelte, frontend/src/routes/person/[id].svelte, frontend/src/routes/tv/[id].svelte
Right now we dont show streamchaser in the titles on the browser. I would like it to be on all views
I would like it to be on all views
_No response_
_No response_
=> Add Streamchaser to all view titles

frontend/src/components/cookie_disclaimer.svelte, frontend/src/routes/__error.svelte, frontend/src/routes/about.svelte, frontend/src/routes/faq.svelte, frontend/src/routes/index.svelte, frontend/src/routes/movie/[id].svelte, frontend/src/routes/person/[id].svelte, frontend/src/routes/tv/[id].svelte, frontend/src/stores/cookie_disclaimer.js
=> Add cookie disclaimer

frontend/src/routes/index.svelte
Generally the multiselects dont fit our site, colour wise they do not fit, and the chips are a random blue color. We want it to fit to our site properly
=> Multiselects gap issues & styling issues

frontend/src/routes/person/[id].svelte, frontend/src/utils.ts
1. Go to person/10980
2. Scroll to Series
3. Look at duplicates
_No response_
=> Duplicate tv and moves in person details-view

frontend/src/components/details/top_card.svelte
=> Write "No providers" when no providers on detail views

frontend/src/components/details/top_card.svelte, frontend/src/components/error.svelte, frontend/src/components/loading/spinner.svelte, frontend/src/routes/person/[id].svelte
This PR Fixes some small fronted things.
* The person view, so it says `Movies` instead of `Movie`.
* Adds country code to the `No providers` text on movie and TV view.
* Fixes the incorrect grammar in the `spinner` after loading longer than 2 seconds.
* Console logs error in the fronted, when an error occurs.
=> Small fixups of frontend

frontend/src/components/details/top_card.svelte
The idea is to have the genres clickable, and after that redirect back to index page, and choose the chosen genre for the user.
The idea is to have the genres clickable, and after that redirect back to index page, and choose the chosen genre for the user.
=> Clickable genres in details view

.pre-commit-config.yaml, backend/app/api.py, backend/app/api_helpers.py, backend/app/cli.py, backend/app/db/crud.py, backend/app/db/database.py, backend/app/db/database_service.py, backend/app/db/models.py, backend/app/db/search.py, backend/app/util.py, backend/tests/test_api.py
The whole backend needs to be formatted for us to begin using it with pre-commit. Will be a huuge change - Shouldn't change any of the logic, just visually
This will make our code look nice and consistent and save the time spend discussing the way the code should be formatted
=> pre-commit black --all-files

frontend/src/components/loading/spinner.svelte
Changes the spinner color to match the newly implemented themes.
=> Change color of spinner to match themes

frontend/src/components/details/top_card.svelte
Makes top cards follow themes!
=> Make top cards follow themes

frontend/src/components/back_to_top_button.svelte, frontend/src/routes/index.svelte
It can get annoying when getting far down in scrolling, and having to go back to the top.
We need a button or something similar that can solve that
=> Go to top button

.env, .gitignore, docker-compose.yml, frontend/Dockerfile, frontend/package-lock.json, frontend/package.json, frontend/svelte.config.js
We want to be able to run different build-stages depending on what environment we are in
I'd like to keep 1 Dockerfile, but be able to chop it up into different stages
https://blog.atulr.com/docker-local-production-image/
=> Implement multistage Dockerfiles

backend/Dockerfile, backend/poetry.lock, backend/pyproject.toml, backend/requirements.txt
It would be nice to not have to pip install our requirements locally/have to manually manage a venv
Replace pip with Poetry and get all the benefits $$$
=> Add poetry

.gitignore, docker-compose.yml, frontend/Dockerfile, frontend/svelte.config.js
It is annoying to have to rebuild the frontend to watch for changes
Get SvelteKit to watch for changes
=> Add Hot Module Replacement to frontend

.pre-commit-config.yaml
Should make it a bit less spammy while still being somewhat up-to-date
* Changes auto-update from weekly to monthly
=> Change pre-commit auto update schedule to monthly

frontend/src/components/error.svelte, frontend/src/components/footer.svelte, frontend/src/components/loading/spinner.svelte, frontend/src/components/no_results.svelte, frontend/src/routes/__error.svelte, frontend/src/routes/__layout.svelte, frontend/src/routes/about.svelte, frontend/src/routes/faq.svelte, frontend/src/routes/index.svelte, frontend/src/routes/movie/[id].svelte, frontend/src/routes/person/[id].svelte, frontend/src/routes/tv/[id].svelte
We have a lot of repeating code like the container-div and navbar/footer
The code should live in a __layout file
_No response_
_No response_
=> Move repeating frontend code into __layout

docker-compose.yml
=> Remove unncessary entrypoints

.env, .github/workflows/main.yml, .gitignore, .pre-commit-config.yaml, backend/Dockerfile, backend/app/config.py, backend/app/main.py, backend/app/routers/providers.py, backend/cli.py, backend/poetry.lock, backend/pyproject.toml, docker-compose.yml, frontend/package-lock.json
Right now there is no difference when we are building the backend in production or in development. Would be awesome to differentiate between the two.
Use multistage in the dockerfile and run based on the target environment.
_No response_
_No response_
=> Implement multistage dockerfile for the backend

frontend/src/components/details/person.svelte, frontend/src/components/details/recommendations.svelte, frontend/src/components/details/seasons.svelte, frontend/src/components/media_search.svelte
* Adjust bg-neutral to see important elements across themes
=> Adjust colors for higher contrast element contrast across themes

backend/app/db/database_service.py
* Fixes provider txt path (the workdir was moved recently and we missed this path)
=> Fix providers_X.txt path

backend/app/api.py, backend/app/routers/movie.py, backend/app/routers/tv.py, backend/app/schemas.py, backend/poetry.lock, backend/pyproject.toml
* Implements httpx
* Changes get_x_by_id (person, movie, tv) to await the request
* Fixes random typo/wrongly typed field that has never worked, but now does :shrug: 
```diff
- aslo_knows_as: str | None
+ also_known_as: list[str] | None
```
=> Implement httpx and await movie, person and tv requests

.pre-commit-config.yaml, .prettierrc, frontend/src/components/details/seasons.svelte, frontend/src/components/details/top_card.svelte, frontend/src/routes/index.svelte, frontend/src/utils.ts
* Changes the Prettier arrowParens behavior to avoid using them
=> Change prettier arrowParens to avoid

frontend/package.json, frontend/src/components/cookie_disclaimer.svelte, frontend/src/components/details/person.svelte, frontend/src/components/details/read_more.svelte, frontend/src/components/details/recommendations.svelte, frontend/src/components/media_search.svelte, frontend/src/components/navbar.svelte, frontend/src/components/no_results.svelte, frontend/src/routes/index.svelte, frontend/src/routes/tv/[id].svelte, frontend/src/types.ts, frontend/src/utils.ts
* Adds interfaces (Provider, Media, Meilisearch)
* Renames media to meilisearch
* Removes redundant type-hints
* Fixes wrong/incomplete typing
* Fixes being lazy `any` and no type errors
=> Add interfaces + Clean weird typing/errors

backend/app/api_helpers.py, backend/app/routers/search.py, backend/app/schemas.py, frontend/yarn.lock
* Removes unused `unique_id()`
* Changes elifs to ifs in search route
* Updates yarn lock(had issues starting the container)
* Changes `any | None` type to `list[str | None]`
=> Fix CodeFactor issues

frontend/src/components/loading/spinner.svelte, frontend/src/components/media_search.svelte
Made to help with some rebasing that was a bit spicy
Real discussion was here #172
=> Fix index showing No results for: <No input> while loading

frontend/src/routes/person/[id].svelte, frontend/src/types.ts
* Filters media with adult=true from the person detail view
=> Filter adult content on person details

frontend/Dockerfile, frontend/package.json, frontend/src/components/back_to_top_button.svelte, frontend/src/components/media_search.svelte, frontend/src/components/navbar.svelte, frontend/src/routes/index.svelte, frontend/tailwind.config.cjs, frontend/yarn.lock
Right now the text color of the `MultiSelects` are not correct when typing in text.
We could use to use `text-color` from `DaisyUI` to fix this.
1. Go to streamchaser.tv
2. Type something in the `MultiSelect` with the different themes.
The colors should look correctly when compared to the top input field.
_No response_
=> Fix text colours in multi-selects

backend/app/db/database_service.py, backend/app/routers/movie.py, backend/app/routers/providers.py, backend/app/routers/tv.py, backend/cli.py
* Replaces the .txt storing with aioredis
=> Move providers to aioredis

backend/app/db/search.py, backend/app/routers/search.py, backend/poetry.lock, backend/pyproject.toml
* Replaces the sync client with an async one for the search endpoint
=> Replace sync client with meilisearch-python-async for our search endpoint

backend/app/main.py, frontend/package.json, frontend/svelte.config.js, frontend/yarn.lock
It would be nice to not have to manually handle pulling the newest master to prod/feature branches to test
I'd like to have Vercel or Netlify host our frontend(both master and feature branches)
Should wait for #146 to be merged, to not have to deal with HMR in prod
=> Setup frontend for serverless

.github/workflows/main.yml, docker-compose.yml, prometheus.yml
=> Setup local Grafana, node_exporter, cAdvisor, Prometheus

backend/app/main.py
* Fixes broken CORS for https://streamchaser.vercel.app
=> Setup CORS to accept the main Vercel URL

.github/ISSUE_TEMPLATE/pull_request_template.md
* Adds a nice yml form for PRs
=> Add pull request form

docker-compose.yml, frontend/src/components/details/person.svelte, frontend/src/components/details/person_media.svelte, frontend/src/components/details/recommendations.svelte, frontend/src/components/details/seasons.svelte, frontend/src/components/details/top_card.svelte, frontend/src/components/media_search.svelte, frontend/src/components/navbar.svelte, frontend/src/routes/index.svelte, frontend/src/routes/movie/[id].svelte, frontend/src/routes/person/[id].svelte, frontend/src/routes/tv/[id].svelte, frontend/src/variables.js, frontend/yarn.lock
* Moves constant variables to same file
* Adjusts image sizes to save bandwidth
Fixes #204 #103
=> Move constant variables to same file + Adjust image sizes to save bandwidth

backend/cli.py
For some reason, we were calling the same func twice... This might be a fairly large performance boost :DDDD :man_facepalming:
=> Remove duplicate update_index() call in full_setup()

backend/app/api.py, backend/app/util.py, backend/cli.py
* Sets up CLI to use the new internal API that's in the making
=> Add CLI to interface with new internal Go API

.github/workflows/main.yml, frontend/package.json, frontend/src/app.html, frontend/yarn.lock
* Fixes weird SvelteKit namechange we didn't catch in CI :see_no_evil:
=> Fix SvelteKit breaking namechange + build as prod in CI

frontend/package.json, frontend/yarn.lock
=> Up SvelteKit and Node adapter to newest

backend/cli.py
=> Add guard clause to handle empty/broken data

internal/main.go
* Handles invalid headers from TMDB
Also mutes the GORM spam - It would show the entire bulk upsert, which is more lines than most terminals can show
=> Handle invalid gzip header

frontend/src/routes/index.svelte
The padding is kinda a lot on the x axis on mobile view, this towns that a bit down
=> Remove some padding on mobile view

backend/cli.py
remove useless try catch - add blacklist as optional argument - make function work when media is not in db
=> Cleanup of remove-and-blacklist cli command

.pre-commit-config.yaml, backend/pyproject.toml
* Makes flake8 able to read 3.10 syntax like match cases
=> Up required Python version to 3.10 - match cases bby!

go_backend/main.go
- Fixes broken CORS for vercel urls
=> Fix broken CORS on go_backend for vercel urls

frontend/src/components/filters.svelte, frontend/src/components/no_results.svelte, frontend/src/routes/index.svelte, frontend/src/stores/filters.js
This adds frontend for TV & Movie filtering
=> Frontend for movie & TV filtering

backend/app/routers/search.py, backend/tests/test_filters.py
* Adds the ability to only get results with providers available
Part of #137
=> Add filter for empty providers + tests

backend/app/api.py, backend/app/routers/country.py, backend/app/routers/image.py, backend/cli.py, backend/pyproject.toml
Changed httpx to use http2 when possible to gain a little speedup
Fixes #282
=> make httpx use http2

backend/app/routers/media.py, backend/app/routers/movie.py, backend/app/routers/person.py, backend/app/routers/providers.py, backend/app/routers/tv.py, frontend/package.json, frontend/src/lib/generated/index.ts, frontend/src/lib/generated/models/Genre.ts, frontend/src/lib/generated/models/HTTPValidationError.ts, frontend/src/lib/generated/models/Media.ts, frontend/src/lib/generated/models/Movie.ts, frontend/src/lib/generated/models/Person.ts, frontend/src/lib/generated/models/TV.ts, frontend/src/lib/generated/models/ValidationError.ts, frontend/yarn.lock
- Generates interfaces from the OpenAPI schema(the ones we define with Pydantic)
=> feat: setup openapi-typescript-codegen

frontend/src/lib/components/details/person.svelte, frontend/src/lib/components/details/person_media.svelte, frontend/src/lib/components/details/recommendations.svelte, frontend/src/lib/components/media_search.svelte, frontend/src/lib/components/navbar/navbar.svelte, frontend/src/lib/components/navbar/phone_navbar.svelte
Fetches data used on details, FAQ, About Us when hovering on link
Requests go brrrr
Fixes #312
=> Prefetch details, FAQ and About Us-pages

frontend/src/routes/+page.svelte, frontend/src/routes/+page.ts, frontend/tests/index.spec.ts
- Moves fetching JS into load()
- Cleans the old logic up a bit
Fixes #276
=> refactor: change index to use load() + some cleaning up

frontend/src/routes/+page.svelte
=> fix: sidescroll on thin phones

frontend/src/routes/+page.ts, frontend/src/routes/movie/[id]/+page.ts, frontend/src/routes/person/[id]/+page.ts, frontend/src/routes/tv/[id]/+page.ts
=> fix: ssr fetch breaking dev

frontend/package.json, frontend/src/lib/components/media_search.svelte, frontend/src/lib/variables.js, frontend/src/routes/+page.svelte, frontend/tailwind.config.cjs, frontend/yarn.lock
- Replaced css hack with css variables to be able to update daisyui
- Updated daisyui to v2.38.1
- Add themes: Night, Business and Coffee
Fixes #279
=> feat!: replace css hack with css variables + update daisyui to v2.38.1

frontend/src/lib/components/theme_selector.svelte
=> fix: remove unused a tags from theme_selector component

frontend/src/lib/components/country_selector.svelte, frontend/src/lib/components/details/person.svelte, frontend/src/lib/components/details/recommendations.svelte, frontend/src/lib/components/details/seasons.svelte, frontend/src/lib/components/details/top_card.svelte, frontend/src/lib/components/footer.svelte, frontend/src/lib/components/media_search.svelte, frontend/src/lib/variables.js, frontend/src/routes/+page.svelte, frontend/tailwind.config.cjs
=> feat: add better colours and dynamic borders

frontend/src/routes/+page.ts, frontend/src/routes/movie/[id]/+page.ts, frontend/src/routes/person/[id]/+page.ts, frontend/src/routes/tv/[id]/+page.ts
=> fix: inconsistency in SSR toggle

docker-compose.yml
- Makes us not have to git stash things in prod 🙈
=> refactor: move traefik middleware to .env

backend/app/db/search.py, backend/app/routers/search.py, backend/tests/test_sort.py, frontend/src/lib/components/filters.svelte, frontend/src/lib/components/media_search.svelte, frontend/src/lib/components/no_results.svelte, frontend/src/lib/stores/filters.js, frontend/src/lib/stores/sorting.js, frontend/src/routes/+page.svelte, frontend/src/stores/sorting.js
* Adds the ability to sort by release date
* Adds tests for release_date and popularity
* Removes popularity as the default sorting - We are back to the custom ranking rules
Part of #248
=> Add release_date sort

frontend/src/lib/components/back_to_top_button.svelte, frontend/src/lib/components/details/person_media.svelte, frontend/src/lib/components/details/read_more.svelte, frontend/src/lib/components/details/recommendations.svelte, frontend/src/lib/components/details/seasons.svelte, frontend/src/lib/components/details/top_card.svelte, frontend/src/routes/+page.svelte
Replaces the seasons component with a component based on Swiper, enabling swipe functionality
Fixes #94
=> feat: rewrite seasons component to be swipeable

frontend/src/lib/components/details/seasons.svelte
Can't use window on the server :D
Fixes #94
=> fix: ReferenceError 'window is not defined' in Seasons-component

frontend/src/lib/components/details/recommendations.svelte, frontend/src/lib/components/details/seasons.svelte
=> fix: make Recommendations use lazy loading

backend/cli.py
=> fix: make sure we index meilisearch in prod 🙈

backend/app/main.py, backend/app/routers/image.py
- Adds 1 year(best practice apparently) to /image
- Adds development performance monitor
=> feat: add Cache-Control max-age to /image

frontend/src/lib/components/head.svelte, frontend/src/routes/+page.svelte
This fixes title on landing page that makes it so that makes it not be `streamchaser - streamchaser`
Also updates description
Fixes #
=> feat: Add new meta description and make title more flexible

frontend/src/lib/stores/providers.js, frontend/src/lib/stores/providers.ts, frontend/src/routes/+page.svelte
Instead of resetting providers completely on changing country, instead only providers not existing in the new country are removed
Fixes #354
=> fix: Removed reset of providers on changing country

frontend/src/lib/components/media_search.svelte
Adds color to the avatar card where the provider images with say +x
=> feat: add a color for + images avatar

.gitignore, docker-compose.yml
https://github.com/meilisearch/meilisearch/releases/tag/v0.29.2
=> fix: up meilisearch to fix duplicate documents

backend/app/db/search.py, backend/cli.py, internal/routes.go, internal/types.go
=> Add translations

backend/app/models.py, backend/app/routers/search.py, frontend/src/lib/components/details/top_card.svelte, frontend/src/lib/components/media_card.svelte, frontend/src/lib/components/media_search.svelte, frontend/src/lib/generated/index.ts, frontend/src/lib/generated/models/Hit.ts, frontend/src/lib/generated/models/Meilisearch.ts, frontend/src/lib/generated/models/Provider.ts, frontend/src/lib/generated/models/Providers.ts, frontend/src/lib/utils.ts
This adds a component that has the media card and types it correctly.
Also types our meilisearch endpoint
=> feat: add media card component with types

backend/app/routers/media.py, frontend/src/lib/components/details/person_media.svelte, frontend/src/lib/components/details/recommendations.svelte, frontend/src/lib/components/loading/spinner.svelte, frontend/src/lib/components/media_card.svelte, frontend/src/lib/types.ts, frontend/src/lib/utils.ts, frontend/src/routes/+page.svelte
=> feat: add providers for details

backend/app/db/search.py
=> feat: improve search for media containing & in titles

frontend/src/routes/+page.ts
Fixes being unable to load the page on master :D
=> fix: 301 on genres by removing trailing /

frontend/src/lib/stores/preferences.ts, frontend/src/lib/utils.ts
Fixes currentCountry in localStorage 
Fixes #
=> fix: fix current country store breaking

backend/app/main.py, backend/app/routers/stats.py
- Adds an endpoint that shows stats about the indexes
=> feat: add meilisearch stats endpoint

internal/routes.go
=> chore: 10x the amount of connections to TMDB

backend/app/db/search.py, internal/types.go
=> feat: add updated at timestamp to meilisearch documents

backend/app/db/search.py
Should make cases like this feel more natural(maybe?)
=> chore: sort over exactness in ranking rule priority

frontend/src/routes/+page.svelte
=> refactor: zero debounce = better experience?

.gitignore, backend/cli.py
Adds a job that creates a sitemap
=> feat: add sitemap that is generated from meilisearch data

frontend/src/lib/components/country_selector.svelte, frontend/src/lib/components/navbar/phone_navbar.svelte
=> fix: unpredictable country selector size

.github/workflows/svelte-check.yml, frontend/package.json, frontend/src/global.d.ts, frontend/src/lib/components/collapse.svelte, frontend/src/lib/components/cookie_disclaimer.svelte, frontend/src/lib/components/details/recommendations.svelte, frontend/src/lib/components/details/seasons.svelte, frontend/src/lib/components/details/top_card.svelte, frontend/src/lib/components/error.svelte, frontend/src/lib/components/navbar/phone_navbar.svelte, frontend/src/lib/components/theme_selector.svelte, frontend/src/lib/stores/preferences.ts, frontend/src/routes/+page.svelte, frontend/tsconfig.json, frontend/yarn.lock
=> feat: setup svelte check and fix errors warning and hints 🧹 

.pre-commit-config.yaml, internal/routes.go
- Adds a pre-commit step(hopefully no more tab/space mixes)
=> feat: add go fmt pre-commit

frontend/src/lib/stores/cookies.ts, frontend/src/routes/+layout.svelte
=> fix: cookies are properly stored in localstorage

backend/Dockerfile, frontend/src/lib/components/country_locator.svelte
=> fix: country http redirect from trailing slash

go_backend/routes.go, internal/routes.go
=> chore: clean-up pre-commit mess

docker-compose.yml
Should fix some bugs :shrug:
Fixes #
=> chore: up meilisearch version to newest

internal/routes.go
=> bug: fix providers on breaking bad(probably more) by removing translation

README.md
Friendship ended with POSTGRES
Now REDIS is my best friend
=> chore: update tech credits

.github/workflows/e2e.yml, docker-compose.yml
=> fix: change faulty environment

backend/app/routers/image.py
*Should* fix the `Error: Not found: <poster_path>`... I hope
=> fix: shorten cache max-age

.gitignore, backend/app/db/search.py, backend/app/models.py, backend/app/routers/media.py, backend/app/routers/search.py, backend/cli.py, backend/tests/conftest.py, backend/tests/test_filters.py, backend/tests/test_sort.py, frontend/src/lib/components/details/top_card.svelte, frontend/src/lib/components/filters.svelte, frontend/src/lib/components/media_card.svelte, frontend/src/lib/components/no_results.svelte, frontend/src/lib/generated/models/Hit.ts, frontend/src/lib/stores/preferences.ts, frontend/src/lib/utils.ts, frontend/src/routes/+page.svelte, frontend/src/routes/movie/[id]/+page.svelte, frontend/src/routes/person/[id]/+page.svelte, frontend/src/routes/tv/[id]/+page.svelte, internal/routes.go, internal/types.go
This adds imdb ratings on all media, furthermore it adds filtering and sorting for imdb ratings
=> feat: add imdb ratings

backend/cli.py, frontend/src/lib/components/details/top_card.svelte
This makes us able to control the min amount of votes media needs to get a imdb rating
Fixes #
=> feat: add min votes required for imdb rating to be added

frontend/src/lib/components/media_card.svelte
Changes the design of the cards showing imdb rating and TV on media cards
=> feat: change design of media card badges

backend/cli.py
=> refactor: move remove_stale_media to own command

.github/pull_request_template.md
We almost never fill them out and I don't feel like enforcing it would add much value
=> chore: remove unused checkboxes from PR template

backend/cli.py
=> fix: add missing await

frontend/package.json, frontend/svelte.config.js, frontend/yarn.lock
=> chore: up sveltekit, svelte and vite versions

frontend/src/lib/components/navbar/navbar.svelte, frontend/src/lib/components/navbar/phone_navbar.svelte, frontend/src/lib/components/sign_in/auth.svelte, frontend/src/lib/stores/stores.ts, frontend/src/lib/types.ts, frontend/src/lib/utils.ts, frontend/src/routes/+layout.ts, frontend/src/routes/profile/+layout.svelte, frontend/src/routes/profile/+page.svelte, frontend/tsconfig.json
This adds sign in with google for our frontend, and keeps the JWT in a store.
THIS IS LOCKED BEHIND A FEATURE FLAG. 
You will `PUBLIC_GOOGLE_ENABLED=true` in your `/frontend/.env` file.
After this enabling this flag, you will need: `PUBLIC_GOOGLE_CLIENT_ID` in your `/frontend/.env` file aswell.
=> feat: initial setup of oauth for frontend

.pre-commit-config.yaml, backend/app/api.py, backend/app/api_helpers.py, backend/app/db/database.py, backend/app/db/database_service.py, backend/app/db/queries/generated.py, backend/app/main.py, backend/app/routers/countries.py, backend/app/routers/country.py, backend/app/routers/genres.py, backend/app/routers/image.py, backend/app/routers/media.py, backend/app/routers/movie.py, backend/app/routers/person.py, backend/app/routers/providers.py, backend/app/routers/search.py, backend/app/routers/stats.py, backend/app/routers/tv.py, backend/app/routers/user.py, backend/app/routers/watch_list.py, backend/app/util.py, backend/cli.py, backend/tests/conftest.py, backend/tests/test_filters.py
Blazingly fast flake8 alternative in... Guess what... RUST OF COURSE!
- Replaces flake8 and reorder_python_imports
https://github.com/charliermarsh/ruff
https://beta.ruff.rs/docs/
If you want some nice performance gains, replace whatever Python linter your editor is using with ruff
=> feat: add ruff to pre-commit

backend/app/db/queries/generated.py, dbschema/default.esdl, dbschema/migrations/00002.edgeql
The provider step of full-setup fails because of a missing logo_path
=> fix: change logo_path to optional (is missing on Filmow)

backend/app/api.py, backend/app/api_helpers.py
=> chore: remove dead old code

.github/dependabot.yml
Added dependency checks for our projects. Hopefully it works this time xD
Fixes #343
=> fix: broken dependabot

frontend/package.json, frontend/svelte.config.js, frontend/yarn.lock
- Removes a couple of old dependencies
=> chore: change to vite preprocess and remove rollup

backend/cli.py, internal/routes.go, internal/types.go
We are too #blazinglyfast
Will hopefully fix our throttling problem
=> fix: slow down our internal job to deal with the TMDB 429 :(

.gitignore, internal/main.go, internal/routes.go
Adds logging info to a file, to easily trace errors.
Fixes #501
=> feat: add formatted logging to file for internal

backend/cli.py, internal/routes.go
Lets us keep track of how the Internal job is doing from the CLI
#503
=> feat: even more dynamic tqdm pbar for update_media!

frontend/package.json, frontend/yarn.lock
=> chore: up playwright dependencies and switch experimental

backend/app/util.py
This makes our backend respond with a 498 Invalid token if it cannot verify it
=> feat: add HTTP exception for handling of auth errors in backend

backend/app/db/database_service.py, backend/app/util.py
This PR makes chunkify python method more accurate & makes full-setup logs not be spammed by country step.
=> feat: add more accurate chunkify & fixup of country fullsetup step

.gitignore, backend/app/api.py, backend/app/db/database_service.py, backend/app/routers/country.py, backend/app/util.py, backend/cli.py
Adds initial version of logging for our backend
Fixes #511
=> feat: add initial logging for backend

backend/app/db/queries/generated.py, backend/app/db/queries/select_user.edgeql, backend/app/db/queries/select_user_providers.edgeql, backend/app/db/queries/update_user_provider_add.edgeql, backend/app/db/queries/update_user_provider_remove.edgeql, backend/app/routers/providers.py, backend/app/routers/user.py, dbschema/default.esdl, dbschema/migrations/00002.edgeql, justfile
* Adds support for adding/removing providers as an user
=> feat: add support for user providers (db add and remove)

.github/workflows/e2e.yml, frontend/package.json, frontend/yarn.lock
=> fix: playwright bump to v1.37.0

frontend/src/app.html, frontend/src/lib/components/back_to_top_button.svelte, frontend/src/lib/components/details/top_card.svelte, frontend/src/lib/stores/preferences.ts, frontend/src/routes/+page.svelte
This makes us keep state when we go back to the index page.
=> feat: keep the state when refreshing or going back to index page

frontend/src/lib/components/head.svelte
=> feat: update the seo description

frontend/src/lib/components/head.svelte
=> fix: html tag closed twice in head

frontend/src/routes/+page.svelte
Right now if you change country it bricks the site. This fixes that issue
=> fix: broken search after changing country

frontend/src/routes/+page.svelte
=> fix: add a browser check in snapshot load

frontend/src/lib/stores/preferences.ts, frontend/tests/index.spec.ts, frontend/tests/movie.spec.ts, frontend/tests/request_mocks.ts, frontend/tests/test_data/harry_p_hits.json
US is now the majority of our users
=> feat: change default country to US
